services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car-rental-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - car-rental-network

    command: "php artisan serve --host 0.0.0.0 --port 8000"

  db:
    image: mysql:8.0
    container_name: car-rental-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel_car_rental
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - car-rental-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: car-rental-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - car-rental-network

networks:
  car-rental-network:
    driver: bridge

volumes:
  db_data: